language: node_js
node_js: node
deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: pixigap.com
    endpoint: pixigap.com.s3-website-us-west-2.amazonaws.com
    region: us-west-2
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
notifications:
    email:
        on_failure: always